import Landing from '@/components/Landing'
import NavbarLanding from '@/components/Navbar'
import Head from 'next/head'
import Mains from "components/main/main"
import Footer from '@/components/Footer'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavbarLanding></NavbarLanding>
        <Landing></Landing>
      <Mains></Mains>
      <Footer></Footer>
    </>
  )
}
